In [1]:
import pandas as pd
import numpy as np

ModuleNotFoundError: No module named 'pandas'

In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_csv("../data/fake_job_postings.csv")
df.head()

IsADirectoryError: [Errno 21] Is a directory: '../data/fake_job_postings.csv'

In [3]:
import os
print(os.listdir("../data"))

['fake_job_postings.csv']

In [4]:
import os
print(os.getcwd())

/workspaces/TrustHire/fake-job-detector/notebooks

In [5]:
import os

print("Current directory:", os.getcwd())
print("Files in parent folder:", os.listdir(".."))
print("Files in data folder:", os.listdir("../data"))

Current directory: /workspaces/TrustHire/fake-job-detector/notebooks
Files in parent folder: ['notebooks', 'frontend', 'backend', 'data', 'README.md']
Files in data folder: ['fake_job_postings.csv']

In [6]:
import pandas as pd

df = pd.read_csv("../data/fake_job_postings.csv")
df.head()

IsADirectoryError: [Errno 21] Is a directory: '../data/fake_job_postings.csv'

In [7]:
import pandas as pd

df = pd.read_csv("/workspaces/TrustHire/fake-job-detector/data/fake_job_postings.csv")
df.head()

IsADirectoryError: [Errno 21] Is a directory: '/workspaces/TrustHire/fake-job-detector/data/fake_job_postings.csv'

In [8]:
import pandas as pd

df = pd.read_csv("../data/fake_job_postings.csv")
df.head()

EmptyDataError: No columns to parse from file

In [1]:
import pandas as pd
import numpy as np

In [2]:
import pandas as pd

df = pd.read_csv("../data/fake_job_postings.csv")
df.head()

EmptyDataError: No columns to parse from file

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import pandas as pd

df = pd.read_csv("../data/fake_job_postings.csv")
df.head()

In [1]:
import pandas as pd

df = pd.read_csv("../data/fake_job_postings.csv")
df.head()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 0: unexpected end of data

In [2]:
import pandas as pd
import numpy as np

In [3]:
import pandas as pd

df = pd.read_csv("../data/fake_job_postings.csv")
df.head()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 0: unexpected end of data

In [4]:
import pandas as pd

df = pd.read_csv("../data/fake_job_postings.csv", encoding="latin1")
df.head()

ParserError: Error tokenizing data. C error: EOF inside string starting at row 13635

In [5]:
import pandas as pd

df = pd.read_csv(
    "../data/fake_job_postings.csv",
    encoding="latin1",
    on_bad_lines="skip"   # 👈 THIS fixes the error
)

df.head()

ParserError: Error tokenizing data. C error: EOF inside string starting at row 16564

In [6]:
import pandas as pd

df = pd.read_csv(
    "../data/fake_job_postings.csv",
    encoding="latin1",
    engine="python",        # 👈 switch to python parser
    on_bad_lines="skip"     # 👈 skip corrupted rows
)

df.head()

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI â Environmental Systems Re...,"EDUCATION:Â Bachelorâs or Masterâs in GIS,...",Our culture is anything but corporateâwe hav...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0

In [7]:
df["text"] = (
    df["title"].fillna("") + " " +
    df["company_profile"].fillna("") + " " +
    df["description"].fillna("") + " " +
    df["requirements"].fillna("")
)

In [8]:
df["text"].iloc[0][:300]

"Marketing Intern We're Food52, and we've created a groundbreaking and award-winning cooking site. We support, connect, and celebrate home cooks, and give them everything they need in one place.We have a top editorial, business, and engineering team. We're focused on using technology to find new and "

In [9]:
import re
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z ]', ' ', text)
    words = text.split()
    words = [w for w in words if w not in stop_words]
    return " ".join(words)

df["clean_text"] = df["text"].apply(clean_text)

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/codespace/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [10]:
df[["text", "clean_text"]].head(2)

,text,clean_text
0,"Marketing Intern We're Food52, and we've creat...",marketing intern food created groundbreaking a...
1,Customer Service - Cloud Video Production 90 S...,customer service cloud video production second...

In [11]:
print("FAKE JOB:\n", df[df["fraudulent"] == 1]["clean_text"].iloc[0][:500])
print("\nREAL JOB:\n", df[df["fraudulent"] == 0]["clean_text"].iloc[0][:500])

FAKE JOB:
 ic e technician staffing amp recruiting done right oil amp energy industry represented candidates automatically granted following perks expert negotiations behalf maximizing compensation package implimenting ongoing increases significant signing bonus refined resources addition potential signing bonuses client companies offer year access anyperk significant corporate discounts cell phones event tickets house cleaning everything inbetween save thousands daily expenditures professional relocation

REAL JOB:
 marketing intern food created groundbreaking award winning cooking site support connect celebrate home cooks give everything need one place top editorial business engineering team focused using technology find new better ways connect people around specific food interests offer superb highly curated information food cooking attract talented home cooks contributors country also publish well known professionals like mario batali gwyneth paltrow danny meyer partnerships whole foods market random hou

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000)

X = vectorizer.fit_transform(df["clean_text"])
y = df["fraudulent"]

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [14]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [15]:
accuracy = model.score(X_test, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.9767582251735587

In [16]:
sample = ["Work from home earn 50000 per week no experience required"]

sample_vec = vectorizer.transform(sample)

pred = model.predict(sample_vec)

print("Prediction:", "Fake" if pred[0] == 1 else "Legit")

Prediction: Legit

In [17]:
def has_scam_words(text):
    scam_words = ["earn money", "work from home", "no experience", "registration fee", "payment required"]
    text = text.lower()
    return int(any(word in text for word in scam_words))

df["scam_flag"] = df["text"].apply(has_scam_words)

In [18]:
from scipy.sparse import hstack

X_text = vectorizer.fit_transform(df["clean_text"])
X = hstack([X_text, df[["scam_flag"]].values])
y = df["fraudulent"]

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

print("Accuracy:", model.score(X_test, y_test))

Accuracy: 0.9779655900996076

In [20]:
sample = ["Work from home earn 50000 per week no experience required"]

sample_vec = vectorizer.transform(sample)

import numpy as np
sample_features = np.hstack([sample_vec.toarray(), [[1]]])  # scam_flag = 1

pred = model.predict(sample_features)

print("Prediction:", "Fake" if pred[0] == 1 else "Legit")

Prediction: Fake

In [21]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      3209
           1       1.00      0.30      0.46       104

    accuracy                           0.98      3313
   macro avg       0.99      0.65      0.72      3313
weighted avg       0.98      0.98      0.97      3313

In [22]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000, class_weight='balanced')
model.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [23]:
y_pred = model.predict(X_test)

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99      3209
           1       0.55      0.88      0.68       104

    accuracy                           0.97      3313
   macro avg       0.78      0.93      0.83      3313
weighted avg       0.98      0.97      0.98      3313

In [24]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred))

[[3135   74]
 [  12   92]]

In [25]:
tests = [
    "Work from home earn 60000 per week no experience required",
    "Google hiring software engineer with experience in Python and ML",
    "Pay registration fee to apply for job",
    "Microsoft internship for 2026 software engineering role"
]

for t in tests:
    vec = vectorizer.transform([t])
    pred = model.predict(vec)[0]
    print(t, "→", "Fake" if pred==1 else "Legit")

ValueError: X has 5000 features, but LogisticRegression is expecting 5001 features as input.

In [26]:
import numpy as np

tests = [
    "Work from home earn 60000 per week no experience required",
    "Google hiring software engineer with experience in Python and ML",
    "Pay registration fee to apply for job",
    "Microsoft internship for 2026 software engineering role"
]

for t in tests:
    # TF-IDF vector
    vec = vectorizer.transform([t])

    # scam flag feature
    scam_flag = 1 if any(word in t.lower() for word in [
        "earn money", "work from home", "no experience", "registration fee", "payment required"
    ]) else 0

    # combine features (same as training)
    combined = np.hstack([vec.toarray(), [[scam_flag]]])

    # prediction
    pred = model.predict(combined)[0]

    print(t, "→", "Fake" if pred == 1 else "Legit")

Work from home earn 60000 per week no experience required → Fake
Google hiring software engineer with experience in Python and ML → Legit
Pay registration fee to apply for job → Fake
Microsoft internship for 2026 software engineering role → Legit

In [27]:
import pickle

pickle.dump(model, open("../backend/model/model.pkl", "wb"))
pickle.dump(vectorizer, open("../backend/model/vectorizer.pkl", "wb"))

In [28]:
loaded_model = pickle.load(open("../backend/model/model.pkl", "rb"))
loaded_vectorizer = pickle.load(open("../backend/model/vectorizer.pkl", "rb"))

print("Model loaded successfully")

Model loaded successfully